services:
  mongodb:
    image: mongo
    container_name: mongo_db
    ports:
      - 27027:27017
    volumes:
      - mongo:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=thai
      - MONGO_INITDB_ROOT_PASSWORD=thai
  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=thai
      - ME_CONFIG_MONGODB_ADMINPASSWORD=thai
      - ME_CONFIG_MONGODB_SERVER=mongodb
    volumes:
      - ./data:/data/db
networks:
  mongo-compose-network:
    driver: bridge